import {
  doc,
  addDoc,
  updateDoc,
  collection,
  serverTimestamp,
  getDoc,
  query,
  where,
  getDocs,
  writeBatch,
  Timestamp,
  type Firestore,
} from 'firebase/firestore';
import type { Order, OrderStatus, OrderEvent, OrderPriority } from '@/lib/types';

// Data for creating an order, without the fields generated by the server
type CreateOrderData = {
  companyId: string;
  clientId: string;
  warehouseId: string;
  orderNumber: string;
  promiseAt: Date;
  priority: OrderPriority;
  items: { sku: string; qty: number }[];
};

/**
 * Creates a new order and an initial 'created' event.
 * Validates for uniqueness of orderNumber within the same company.
 * Calculates totalItems and totalUnits.
 */
export async function createOrder(
  db: Firestore,
  data: CreateOrderData,
  userId: string
): Promise<string> {
  // Validate for uniqueness of orderNumber within the company
  const q = query(
    collection(db, 'orders'),
    where('companyId', '==', data.companyId),
    where('orderNumber', '==', data.orderNumber)
  );
  const existingOrderSnap = await getDocs(q);
  if (!existingOrderSnap.empty) {
    throw new Error(`Ya existe una orden con el número "${data.orderNumber}" en esta compañía.`);
  }

  if (!data.items || data.items.length === 0) {
    throw new Error('La orden debe contener al menos un ítem.');
  }

  // Calculate totals
  const totalItems = data.items.length;
  const totalUnits = data.items.reduce((sum, item) => sum + item.qty, 0);

  const batch = writeBatch(db);
  
  // 1. Create the order document
  const orderRef = doc(collection(db, 'orders'));
  const newOrder: Omit<Order, 'id'> = {
    ...data,
    promiseAt: Timestamp.fromDate(data.promiseAt),
    status: 'created',
    totalItems,
    totalUnits,
    createdAt: serverTimestamp() as Timestamp,
    updatedAt: serverTimestamp() as Timestamp,
    createdBy: userId,
  };
  batch.set(orderRef, newOrder);

  // 2. Create the initial order event
  const eventRef = doc(collection(db, 'orders', orderRef.id, 'events'));
  const initialEvent: Omit<OrderEvent, 'id'> = {
    companyId: data.companyId,
    type: 'created',
    message: 'La orden ha sido creada.',
    createdAt: serverTimestamp(),
    createdBy: userId,
  };
  batch.set(eventRef, initialEvent);
  
  // Commit the batch
  await batch.commit();
  
  return orderRef.id;
}

/**
 * Lists all orders for a given company, with optional filters.
 */
export async function listOrders(
  db: Firestore,
  companyId: string,
  filters?: { status?: OrderStatus }
): Promise<Order[]> {
  const constraints = [where('companyId', '==', companyId)];
  if (filters?.status) {
    constraints.push(where('status', '==', filters.status));
  }
  
  const q = query(collection(db, 'orders'), ...constraints);
  const querySnapshot = await getDocs(q);
  
  return querySnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as Order));
}

/**
 * Gets a single order by its ID.
 */
export async function getOrder(db: Firestore, orderId: string): Promise<Order | null> {
  const orderRef = doc(db, 'orders', orderId);
  const orderSnap = await getDoc(orderRef);
  
  if (!orderSnap.exists()) {
    return null;
  }
  
  return { id: orderSnap.id, ...orderSnap.data() } as Order;
}


type AddOrderEventData = Omit<OrderEvent, 'id' | 'createdAt' | 'companyId'>;
/**
 * Adds a new event to an order's timeline.
 * It fetches the order to ensure the companyId is correctly sourced.
 */
export async function addOrderEvent(
  db: Firestore,
  orderId: string,
  eventData: AddOrderEventData
): Promise<void> {
  const orderRef = doc(db, 'orders', orderId);
  const orderSnap = await getDoc(orderRef);

  if (!orderSnap.exists()) {
    throw new Error("Order not found, cannot add event.");
  }
  const orderData = orderSnap.data();

  const eventsCollection = collection(db, 'orders', orderId, 'events');
  await addDoc(eventsCollection, {
    ...eventData,
    companyId: orderData.companyId, // Source companyId from the parent order
    createdAt: serverTimestamp(),
  });
}

/**
 * Updates the status of an order and adds a corresponding event.
 * Also updates the `updatedAt` timestamp.
 */
export async function updateOrderStatus(
  db: Firestore,
  orderId: string,
  status: OrderStatus,
  userId: string
): Promise<void> {
  const orderRef = doc(db, 'orders', orderId);
  const orderSnap = await getDoc(orderRef);

  if (!orderSnap.exists()) {
    throw new Error("Order not found");
  }
  const orderData = orderSnap.data();

  const batch = writeBatch(db);

  // 1. Update the order status and updatedAt timestamp
  batch.update(orderRef, { 
    status: status,
    updatedAt: serverTimestamp()
  });

  // 2. Add an order event
  const eventRef = doc(collection(db, 'orders', orderId, 'events'));
  const newEvent: Omit<OrderEvent, 'id'> = {
    companyId: orderData.companyId, // Use companyId from the fetched order
    type: status,
    message: `El estado de la orden cambió a: ${status}`,
    createdAt: serverTimestamp(),
    createdBy: userId,
  };
  batch.set(eventRef, newEvent);

  await batch.commit();
}
