import {
  doc,
  addDoc,
  updateDoc,
  collection,
  serverTimestamp,
  getDoc,
  query,
  where,
  getDocs,
  writeBatch,
  Timestamp,
  increment,
  type Firestore,
} from 'firebase/firestore';
import type { Order, OrderStatus, OrderEvent, OrderPriority } from '@/lib/types';

// Data for creating an order, without the fields generated by the server
type CreateOrderData = {
  companyId: string;
  clientId: string;
  warehouseId: string;
  orderNumber: string;
  promiseAt: Date;
  priority: OrderPriority;
  items: { sku: string; qty: number }[];
};

/**
 * Creates a new order and an initial 'created' event.
 * Validates for uniqueness of orderNumber within the same company.
 * Calculates totalItems and totalUnits.
 * Updates the KPI snapshot.
 */
export async function createOrder(
  db: Firestore,
  data: CreateOrderData,
  userId: string
): Promise<string> {
  // Validate for uniqueness of orderNumber within the company
  const q = query(
    collection(db, 'orders'),
    where('companyId', '==', data.companyId),
    where('orderNumber', '==', data.orderNumber)
  );
  const existingOrderSnap = await getDocs(q);
  if (!existingOrderSnap.empty) {
    throw new Error(`Ya existe una orden con el número "${data.orderNumber}" en esta compañía.`);
  }

  if (!data.items || data.items.length === 0) {
    throw new Error('La orden debe contener al menos un ítem.');
  }

  // Calculate totals
  const totalItems = data.items.length;
  const totalUnits = data.items.reduce((sum, item) => sum + item.qty, 0);

  const batch = writeBatch(db);
  
  // 1. Create the order document
  const orderRef = doc(collection(db, 'orders'));
  const newOrder: Omit<Order, 'id'> = {
    ...data,
    promiseAt: Timestamp.fromDate(data.promiseAt),
    status: 'created',
    totalItems,
    totalUnits,
    createdAt: serverTimestamp() as Timestamp,
    updatedAt: serverTimestamp() as Timestamp,
    createdBy: userId,
  };
  batch.set(orderRef, newOrder);

  // 2. Create the initial order event
  const eventRef = doc(collection(db, 'orders', orderRef.id, 'events'));
  const initialEvent: Omit<OrderEvent, 'id'> = {
    companyId: data.companyId,
    type: 'created',
    message: 'La orden ha sido creada.',
    createdAt: serverTimestamp(),
    createdBy: userId,
  };
  batch.set(eventRef, initialEvent);
  
  // 3. Update KPI Snapshot
  const kpiRef = doc(db, 'kpi_snapshots', data.companyId);
  batch.set(kpiRef, {
    ordersToday: increment(1),
    ordersInProgress: increment(1),
    updatedAt: serverTimestamp()
  }, { merge: true });

  // Commit the batch
  await batch.commit();
  
  return orderRef.id;
}

/**
 * Lists all orders for a given company, with optional filters.
 */
export async function listOrders(
  db: Firestore,
  companyId: string,
  filters?: { status?: OrderStatus }
): Promise<Order[]> {
  const constraints = [where('companyId', '==', companyId)];
  if (filters?.status) {
    constraints.push(where('status', '==', filters.status));
  }
  
  const q = query(collection(db, 'orders'), ...constraints);
  const querySnapshot = await getDocs(q);
  
  return querySnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as Order));
}

/**
 * Gets a single order by its ID.
 */
export async function getOrder(db: Firestore, orderId: string): Promise<Order | null> {
  const orderRef = doc(db, 'orders', orderId);
  const orderSnap = await getDoc(orderRef);
  
  if (!orderSnap.exists()) {
    return null;
  }
  
  return { id: orderSnap.id, ...orderSnap.data() } as Order;
}


type AddOrderEventData = Omit<OrderEvent, 'id' | 'createdAt' | 'companyId'>;
/**
 * Adds a new event to an order's timeline.
 * It fetches the order to ensure the companyId is correctly sourced.
 */
export async function addOrderEvent(
  db: Firestore,
  orderId: string,
  eventData: AddOrderEventData
): Promise<void> {
  const orderRef = doc(db, 'orders', orderId);
  const orderSnap = await getDoc(orderRef);

  if (!orderSnap.exists()) {
    throw new Error("Order not found, cannot add event.");
  }
  const orderData = orderSnap.data();

  const eventsCollection = collection(db, 'orders', orderId, 'events');
  await addDoc(eventsCollection, {
    ...eventData,
    companyId: orderData.companyId, // Source companyId from the parent order
    createdAt: serverTimestamp(),
  });
}

const IN_PROGRESS_STATUSES: OrderStatus[] = ['created', 'received', 'picking', 'packed'];
const FINAL_STATUSES: OrderStatus[] = ['delivered', 'cancelled'];
/**
 * Updates the status of an order and adds a corresponding event.
 * Also updates the `updatedAt` timestamp and the KPI snapshot.
 */
export async function updateOrderStatus(
  db: Firestore,
  orderId: string,
  newStatus: OrderStatus,
  userId: string
): Promise<void> {
  const orderRef = doc(db, 'orders', orderId);
  
  const orderSnap = await getDoc(orderRef);
  if (!orderSnap.exists()) {
    throw new Error("Order not found");
  }
  const order = { id: orderSnap.id, ...orderSnap.data() } as Order;
  const oldStatus = order.status;

  // Don't do anything if status is the same
  if (oldStatus === newStatus) {
    return;
  }

  const batch = writeBatch(db);

  // 1. Update the order status and updatedAt timestamp
  batch.update(orderRef, { 
    status: newStatus,
    updatedAt: serverTimestamp()
  });

  // 2. Add an order event
  const eventRef = doc(collection(db, 'orders', orderId, 'events'));
  const newEvent: Omit<OrderEvent, 'id'> = {
    companyId: order.companyId,
    type: newStatus,
    message: `El estado de la orden cambió a: ${newStatus}`,
    createdAt: serverTimestamp(),
    createdBy: userId,
  };
  batch.set(eventRef, newEvent);

  // 3. Update KPI Snapshot
  const kpiRef = doc(db, 'kpi_snapshots', order.companyId);
  const kpiUpdates: { [key: string]: any } = { updatedAt: serverTimestamp() };

  const wasInProgress = IN_PROGRESS_STATUSES.includes(oldStatus);
  const isNowInProgress = IN_PROGRESS_STATUSES.includes(newStatus);
  const wasDelayed = order.promiseAt.toDate() < new Date() && !FINAL_STATUSES.includes(oldStatus);
  const isNowFinal = FINAL_STATUSES.includes(newStatus);

  if (wasInProgress && !isNowInProgress) {
    kpiUpdates.ordersInProgress = increment(-1);
  } else if (!wasInProgress && isNowInProgress) {
    kpiUpdates.ordersInProgress = increment(1);
  }

  if (wasDelayed && isNowFinal) {
    kpiUpdates.ordersDelayed = increment(-1);
  }
  
  batch.set(kpiRef, kpiUpdates, { merge: true });


  await batch.commit();
}
